[[mdoodz]]
arch = "aarch64"
git-tree-sha1 = "17a7b7836fb9b26817837589a23ed7ac709e36e8"
os = "macos"

    [[mdoodz.download]]
    sha256 = "b2055c92f1a419b0958d8f0833dba26859a18f23bb4a6b523a2fb7091925a2c2"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.7.2+0/mdoodz.v0.7.2.aarch64-apple-darwin.tar.gz"
[[mdoodz]]
arch = "aarch64"
git-tree-sha1 = "b0ce92d7db65dee092fdbf067f7951020a37d732"
libc = "glibc"
os = "linux"

    [[mdoodz.download]]
    sha256 = "095645622a487a2ec6c3e67dfdd5b9a9498696d42b7c4d368a2f192cf1bb5867"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.7.2+0/mdoodz.v0.7.2.aarch64-linux-gnu.tar.gz"
[[mdoodz]]
arch = "i686"
git-tree-sha1 = "491602888d8c58c2450cbde02e42ac99c83e7c2a"
os = "windows"

    [[mdoodz.download]]
    sha256 = "0d87de7e799ac4fce5763afd117df653d9d3f49587c61233fc3c64c2dd8a54b6"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.7.2+0/mdoodz.v0.7.2.i686-w64-mingw32.tar.gz"
[[mdoodz]]
arch = "x86_64"
git-tree-sha1 = "b44a4362e6d1eedf77f93fc81c675a3e2e48a464"
os = "macos"

    [[mdoodz.download]]
    sha256 = "bd3af01915012d3a8694e42735613d822d1fec3e82b057d6fefc18c15c7d2ef4"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.7.2+0/mdoodz.v0.7.2.x86_64-apple-darwin.tar.gz"
[[mdoodz]]
arch = "x86_64"
git-tree-sha1 = "08042c7f065f904a8a63a167eaed4580df552eab"
libc = "glibc"
os = "linux"

    [[mdoodz.download]]
    sha256 = "a99987a5db8452b2a4ccd31236be16f84e9bb09f9517ff0ba8f4e19e9a51f615"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.7.2+0/mdoodz.v0.7.2.x86_64-linux-gnu.tar.gz"
[[mdoodz]]
arch = "x86_64"
git-tree-sha1 = "ccf6f80360907b5efbae9826293d0f7989f591a8"
os = "windows"

    [[mdoodz.download]]
    sha256 = "b3c17ebf4b3453dff10fb968521f243080190fa8194bbbe305952d6ea0af4026"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.7.2+0/mdoodz.v0.7.2.x86_64-w64-mingw32.tar.gz"
