[[mdoodz]]
arch = "aarch64"
git-tree-sha1 = "ffc0a9c099761603bac9c32a6553ac7dff0736ba"
os = "macos"

    [[mdoodz.download]]
    sha256 = "b8afe365d4fd38b88a0129190fe878b88e943f9e89c23153b4a858de0d1cf0ea"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.7.1+0/mdoodz.v0.7.1.aarch64-apple-darwin.tar.gz"
[[mdoodz]]
arch = "aarch64"
git-tree-sha1 = "458becdfe561ce98d8e478addb82b5486488dfcb"
libc = "glibc"
os = "linux"

    [[mdoodz.download]]
    sha256 = "bfa7f1c838bcb3eb616c5e7070df8ba139edf7921fdf78077790df53f9540088"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.7.1+0/mdoodz.v0.7.1.aarch64-linux-gnu.tar.gz"
[[mdoodz]]
arch = "i686"
git-tree-sha1 = "0ae7fa5aa39062c71a28396aa778d07f06ef2941"
os = "windows"

    [[mdoodz.download]]
    sha256 = "d2963347b184561546c48cd3c75d2493c05d8e88c52bb85925068fb32586a6fa"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.7.1+0/mdoodz.v0.7.1.i686-w64-mingw32.tar.gz"
[[mdoodz]]
arch = "x86_64"
git-tree-sha1 = "fb46808aeb2416c82cbf855a88fe039c6de71786"
os = "macos"

    [[mdoodz.download]]
    sha256 = "adc60713621f2715dd32f1ba25dedb34548274463c68c8fe9a87493815e5a275"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.7.1+0/mdoodz.v0.7.1.x86_64-apple-darwin.tar.gz"
[[mdoodz]]
arch = "x86_64"
git-tree-sha1 = "26b15e02f83ca7a6ab80ed11ea71b338d761fa57"
libc = "glibc"
os = "linux"

    [[mdoodz.download]]
    sha256 = "181f3e9334245ddecc8dda7246f66b49212006eec51376fd0c674407145f941e"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.7.1+0/mdoodz.v0.7.1.x86_64-linux-gnu.tar.gz"
[[mdoodz]]
arch = "x86_64"
git-tree-sha1 = "e77b09579634b1ee75a15d19db9153d4edcbd9f4"
os = "windows"

    [[mdoodz.download]]
    sha256 = "b72a4f168205e39a6e58cbb7b6d65250280c42488cd7f6ed06565cc481771be8"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.7.1+0/mdoodz.v0.7.1.x86_64-w64-mingw32.tar.gz"
