[[mdoodz]]
arch = "aarch64"
git-tree-sha1 = "415f74ba838639ba8fd989199eb7acb0390c60a8"
os = "macos"

    [[mdoodz.download]]
    sha256 = "52a6bf2445515140252751f1ecfdddd9cff75d1c610924d2bf64c7381b4d1396"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.7.4+0/mdoodz.v0.7.4.aarch64-apple-darwin.tar.gz"
[[mdoodz]]
arch = "aarch64"
git-tree-sha1 = "ac33e8caa5d91924ce4871b263b661406d2ea3a8"
libc = "glibc"
os = "linux"

    [[mdoodz.download]]
    sha256 = "e2fb3866900e2ca1b0094ad4847208243d9029adfbcdd74b7bbfe8dba520e757"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.7.4+0/mdoodz.v0.7.4.aarch64-linux-gnu.tar.gz"
[[mdoodz]]
arch = "i686"
git-tree-sha1 = "dc9720a9033608fb0d739f1da6d2e13d7957ecf7"
os = "windows"

    [[mdoodz.download]]
    sha256 = "757dd8912bcb3d2bc6f960dc71d9aa0daced1dff3eb4f33da5239d763c9c4558"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.7.4+0/mdoodz.v0.7.4.i686-w64-mingw32.tar.gz"
[[mdoodz]]
arch = "x86_64"
git-tree-sha1 = "be28ea5790dd3e2212934052e7fdf845760d07fd"
os = "macos"

    [[mdoodz.download]]
    sha256 = "dd490b34b5aa80e9e6c911214e61f46c705bca14088c4e172e10c6837cc5fb61"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.7.4+0/mdoodz.v0.7.4.x86_64-apple-darwin.tar.gz"
[[mdoodz]]
arch = "x86_64"
git-tree-sha1 = "18f03f569f7061d70e9350d46c11c2ab042e0be4"
libc = "glibc"
os = "linux"

    [[mdoodz.download]]
    sha256 = "9f70d913c596bf7b2422a7329ac94e599aa43cba2d6011c6ccaa487dddcf4a65"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.7.4+0/mdoodz.v0.7.4.x86_64-linux-gnu.tar.gz"
[[mdoodz]]
arch = "x86_64"
git-tree-sha1 = "8d4a6dca669c117a9bba933fdb0413b660938f70"
os = "windows"

    [[mdoodz.download]]
    sha256 = "8aef1cf05a1b5c289ffa5b1092b30826aa9c6d86eca18c00c421ef31c9e97a97"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.7.4+0/mdoodz.v0.7.4.x86_64-w64-mingw32.tar.gz"
