[[mdoodz]]
arch = "aarch64"
git-tree-sha1 = "e6ec97ffdeca2052f61bcf556c6f4f31bcb9a1fa"
os = "macos"

    [[mdoodz.download]]
    sha256 = "9cba6c517d12bffda5c6a6bdd098443b107d8ec0ce5529818bb1ee56db7eb716"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.7.3+0/mdoodz.v0.7.3.aarch64-apple-darwin.tar.gz"
[[mdoodz]]
arch = "aarch64"
git-tree-sha1 = "1728825e30db525a2e840d7cf9c6f38a871d7e77"
libc = "glibc"
os = "linux"

    [[mdoodz.download]]
    sha256 = "ad4f15da1a49f7094370d8bd865e084ae7c58c99fe5a15d92504c5919223279a"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.7.3+0/mdoodz.v0.7.3.aarch64-linux-gnu.tar.gz"
[[mdoodz]]
arch = "i686"
git-tree-sha1 = "15f07085cf9536fcc626d44955b0f42d53dd0e48"
os = "windows"

    [[mdoodz.download]]
    sha256 = "e690db47dd73a695410ff05f494be4c97f855dc567674ad9005833d894d1c09f"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.7.3+0/mdoodz.v0.7.3.i686-w64-mingw32.tar.gz"
[[mdoodz]]
arch = "x86_64"
git-tree-sha1 = "5c1dbdaebfc6089430a0554a770653a18e3c12f3"
os = "macos"

    [[mdoodz.download]]
    sha256 = "eb287a4095dec42a9d84cb648914f2275bb662fb1a228db65c7238de833180aa"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.7.3+0/mdoodz.v0.7.3.x86_64-apple-darwin.tar.gz"
[[mdoodz]]
arch = "x86_64"
git-tree-sha1 = "520f1a91f3f6fa7d8ba97b4d834ce98ff8b32a24"
libc = "glibc"
os = "linux"

    [[mdoodz.download]]
    sha256 = "bd117a215267b28ee9ddf0a44ea63b42cda1cf2276a6c01879febcfae8adfce9"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.7.3+0/mdoodz.v0.7.3.x86_64-linux-gnu.tar.gz"
[[mdoodz]]
arch = "x86_64"
git-tree-sha1 = "f51269d4378f64799ef86446f66b2450187fbcfc"
os = "windows"

    [[mdoodz.download]]
    sha256 = "f45b37e1532481f4d7e797b8267b2e85ba25562fdf61de68fabdfc6a79382ba0"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.7.3+0/mdoodz.v0.7.3.x86_64-w64-mingw32.tar.gz"
