[[mdoodz]]
arch = "aarch64"
git-tree-sha1 = "5235e70910fccbe6bd20118c3f87ed77d42fd37b"
os = "macos"

    [[mdoodz.download]]
    sha256 = "d6ae85ea53d8c111a22e98a3c1e832f5997e1a3aee52a4d7a71b8676e3ffcf91"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.5.0+0/mdoodz.v0.5.0.aarch64-apple-darwin.tar.gz"
[[mdoodz]]
arch = "aarch64"
git-tree-sha1 = "74c6a54408f03cde969dce3f8dc4c4fbbd3236a4"
libc = "glibc"
os = "linux"

    [[mdoodz.download]]
    sha256 = "3cfe6983069421f7d11f3005562dae976f1b5f5a934bce91047847e1ecf4db99"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.5.0+0/mdoodz.v0.5.0.aarch64-linux-gnu.tar.gz"
[[mdoodz]]
arch = "i686"
git-tree-sha1 = "831c4ac791e8a06f38d16b8ad5b6e646d0cee88c"
os = "windows"

    [[mdoodz.download]]
    sha256 = "dac3ef1913aaab2d7d5b0856cf4d1f1e6bdb82111a235a0d6e238eb8a15e6892"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.5.0+0/mdoodz.v0.5.0.i686-w64-mingw32.tar.gz"
[[mdoodz]]
arch = "x86_64"
git-tree-sha1 = "916b7aaa2985af96040a8df553e50879fc1805e0"
os = "macos"

    [[mdoodz.download]]
    sha256 = "7a35799a61e9f7fa7a49ab75f96de20c7b06caf921ea12eff89de779ed2141d3"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.5.0+0/mdoodz.v0.5.0.x86_64-apple-darwin.tar.gz"
[[mdoodz]]
arch = "x86_64"
git-tree-sha1 = "96668532814691629f2a35a9674d8437780b107d"
libc = "glibc"
os = "linux"

    [[mdoodz.download]]
    sha256 = "a08d52054cad5ffe0ffb9248b4ae4e550e53afe85a9bf115a674568d3792cc39"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.5.0+0/mdoodz.v0.5.0.x86_64-linux-gnu.tar.gz"
[[mdoodz]]
arch = "x86_64"
git-tree-sha1 = "7771ebafce10965246e163bd3ca391ca6a2b2c81"
os = "windows"

    [[mdoodz.download]]
    sha256 = "e70494b1dbc967a8ff84c05acefd78ac834a484db410daffe14f2c68980345d2"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.5.0+0/mdoodz.v0.5.0.x86_64-w64-mingw32.tar.gz"
