[[mdoodz]]
arch = "aarch64"
git-tree-sha1 = "5c2b1b6fe1c65e27a2baec517a484184709c3174"
os = "macos"

    [[mdoodz.download]]
    sha256 = "a97312bf77f770641eab9c8fd59d23dff059bbccab09c09f94822b1368c2168f"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.1.0+1/mdoodz.v0.1.0.aarch64-apple-darwin.tar.gz"
[[mdoodz]]
arch = "aarch64"
git-tree-sha1 = "c5ba2af1cc7bf3947b37203f6d2083cf0fe511d4"
libc = "glibc"
os = "linux"

    [[mdoodz.download]]
    sha256 = "c76984eb2ead135eb311549cb7990413ef76edf70368bb5e59386dc9c5653ab0"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.1.0+1/mdoodz.v0.1.0.aarch64-linux-gnu.tar.gz"
[[mdoodz]]
arch = "x86_64"
git-tree-sha1 = "ee674a70e6ff33ae2dfacf7675676ded48274ab1"
os = "macos"

    [[mdoodz.download]]
    sha256 = "1438ac22b43e1aab788c8569c1b9f69fcb7cf205eefcb856234a64c2067d5317"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.1.0+1/mdoodz.v0.1.0.x86_64-apple-darwin.tar.gz"
[[mdoodz]]
arch = "x86_64"
git-tree-sha1 = "6bad95c04f8a9d1027fbf2da91b80ce29a9c2d51"
libc = "glibc"
os = "linux"

    [[mdoodz.download]]
    sha256 = "dcf45e0e5955d406ae5f7b58229ef16f6ba66fa91b3a53dc31e33f44e63e9753"
    url = "https://github.com/JuliaBinaryWrappers/mdoodz_jll.jl/releases/download/mdoodz-v0.1.0+1/mdoodz.v0.1.0.x86_64-linux-gnu.tar.gz"
