# Autogenerated wrapper script for mdoodz_jll for x86_64-apple-darwin
export libmdoodz

using CXSparse_jll
using HDF5_jll
using SuiteSparse_jll
using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("mdoodz")
JLLWrappers.@declare_library_product(libmdoodz, "@rpath/libmdoodz.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CXSparse_jll, HDF5_jll, SuiteSparse_jll, LLVMOpenMP_jll)
    JLLWrappers.@init_library_product(
        libmdoodz,
        "lib/libmdoodz.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
